### ISSUE TITLE
Navbar Toggler custom links auto-scroll back to top

### ISSUE THREAD

**Issue by micreativespace** [babobski/Bootstrap-on-WordPress#39]
**Description (small description where the bug is about):**  

In mobile view, when I click a custom link to an anchor on the page, it scrolls there. Does not auto close. Then when closed, it auto scrolls back to the top.

**Expected result:**  
It should scroll to the anchor and auto close. And stay there.

**Actual result:**  
Auto scrolls back to top

**Steps to reproduce**  
Install theme, add a custom link to an anchor on the page. Go into mobile view. Click the link form mobile menu.

**Comment by micreativespace** [comment]
Its only when using the mobile navbar toggler

**Comment by babobski** [comment]
That's because it's using the offcanvas component from bootstrap, when opened it will put a overflow hidden on the body tag.
This is preventing you're scroll to anchor action, for this to work you need a other approach.

You will have to add a event listener to you're custom link and then close the offcanvas manually.
You will then have to listen on the event 'hidden.bs.offcanvas' from the offcanvas en then scroll to the anchor you;re self.
Because you're probability are using jquery so you could something like this:

```javascript
let offCanvas = $('#primaryNav');
let anchor = '';

$('.cusom-link').on('click', (event) => {
  // Blocking the default link behaviour
  event.preventDefault(); 
  
  // Hidding the offcanvas
  offCanvas.offcanvas('hide');
  
  // Storing the anchor to scroll to
  anchor = $(event.target).attr('href');
  
});

// Listen to the offcanvas closing event
offCanvas.on('hidden.bs.offcanvas', () => {
  // Check if anchor isset
  if (anchor.length > 0) {
    // Getting the offset top from the anchor
    const anchorOffsetTop = $(anchor).offset().top;
    
    // scroll to the anchor
    $('html, body').animate({
      scrollTop: anchorOffsetTop
    }, 800).promise().done(() => {
      // When done you can clear the stored anchor
      anchor = '';
    });
  }
});
```
Small disclaimer, i didn't test the code

**Comment by micreativespace** [comment]
Thanks for the info. I will give that a go, I am self taught so not so easy for me. Where should I place this? In the header or footer?

**Comment by babobski** [comment]
It would be better for performance reasons to load it in the footer, but it could be placed in the header after jQuery is loaded.

**Comment by micreativespace** [comment]
Hi There,

I wrapped it in a script tag and placed it in footer - it worked the first time then stopped working. Any ideas?

**Comment by babobski** [comment]
Maybe do you see if you have a error in you're console when you click it the second time?
